export const surpriseMePrompts = [
  'A koala on a tiny skateboard doing tricks, digital art',
  'A unicorn shopping for groceries in a futuristic city, cyberpunk style',
  'A giant octopus playing chess with a human on a beach, watercolor painting',
  'A magical library with floating books, in the style of Studio Ghibli',
  'A steampunk submarine exploring an underwater city, digital art',
  'A lion wearing a top hat, sitting on a velvet chair, oil painting',
  'A futuristic motorcycle racing through a neon-lit city at night, cyberpunk',
  'A giraffe sipping a latte in a Parisian cafe, digital art',
  'A time-traveling dog in Victorian attire, sepia-toned photography',
  'A futuristic city with glowing skyscrapers and flying cars, concept art',
  'A dragon made of clouds soaring through the sky at sunset, digital painting',
  'A panda astronaut planting a flag on the moon, retro-futuristic style',
  'A mermaid playing electric guitar under the sea, neon-lit scene',
  'A giant mushroom village with tiny fairy inhabitants, fantasy illustration',
  'A cat wearing aviator sunglasses flying a biplane, vintage style',
  'A giant robot doing yoga in a Zen garden, digital painting',
  'A phoenix rising from a volcano, dynamic comic book style',
  'A cyborg ballerina dancing in a futuristic theater, neon-lit',
  'A castle made of candy, surrounded by a chocolate river, pastel colors',
  'A robot chef preparing a meal in a futuristic kitchen, digital art'
];
